# Generated by Django 2.0.13 on 2020-01-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    def init_sources_counter(apps, schema_editor):
        SourcesCounter = apps.get_model("sources", "SourcesCounter")

        if (len(SourcesCounter.objects.all()) == 0):
            db_alias = schema_editor.connection.alias
            # Set a counter taking into account the 21 sources fom the skinny tool.
            SourcesCounter.objects.using(db_alias).bulk_create([SourcesCounter(count=21)])
            print('SourcesCounter instance created')
        else:
            print('SourcesCounter already exists')

    operations = [
        migrations.RunPython(init_sources_counter)
    ]
