# Generated by Django 2.0.13 on 2020-04-06 13:20

from django.db import migrations

def add_custom_permissions(apps, schema_editor):
    Store = apps.get_model('rdflib_django', 'Store')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get_for_model(Store)
    db_alias = schema_editor.connection.alias
    Permission.objects.using(db_alias).bulk_create([
        Permission(codename='upload_source', name='Can upload Source', content_type=content_type),
        Permission(codename='delete_source', name='Can delete Source', content_type=content_type),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_init_counter'),
    ]

    operations = [
        migrations.RunPython(add_custom_permissions),
    ]
