# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-10 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startIndex', models.IntegerField()),
                ('endIndex', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publicationDate', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.Source'),
        ),
    ]
