# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='text',
            field=models.CharField(default='default', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotations', to='annotation.Source'),
        ),
    ]
