# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-25 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0002_auto_20190412_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
