# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_annotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.Source'),
        ),
    ]
