# Generated by Django 2.0.13 on 2020-04-06 13:31

from django.db import migrations

def add_custom_permissions(apps, schema_editor):
    Store = apps.get_model('rdflib_django', 'Store')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get_for_model(Store)
    db_alias = schema_editor.connection.alias
    Permission.objects.using(db_alias).bulk_create([
        Permission(codename='view_all_annotations', name='Can view all annotations', content_type=content_type)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_editcounter'),
        ('rdflib_django', '0002_auto_20181112_1317'),
    ]

    operations = [
        migrations.RunPython(add_custom_permissions),
    ]
