# Generated by Django 2.0.13 on 2021-07-01 15:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_init_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
