# Generated by Django 2.0.13 on 2020-05-06 13:29
from django.db import migrations


def add_custom_permissions(apps, schema_editor):
    Store = apps.get_model('rdflib_django', 'Store')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get_for_model(Store)
    db_alias = schema_editor.connection.alias
    instance = Permission(
        codename='sparql_update',
        name='Can SPARQL-Update',
        content_type=content_type
    )
    Permission.objects.using(db_alias).bulk_create([instance])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_custom_permissions)
    ]
